core/urls.py
from django.urls import path
from django.contrib import admin
from .views import  (
CheckoutView,
ItemDetailView,
#HomeView,
add_to_cart,
OrderSummaryView,
remove_from_cart,
remove_single_item_from_cart,
home
)




app_name = 'core'

urlpatterns = [
    #path('', HomeView.as_view(), name='home'),
    path('', home, name='home'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mpesa.urls import mpesa_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('mpesa/', include(mpesa_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django.db.models import Model
from django.db.models.signals import post_save






LABEL_CHOICES = [
    ('P', 'primary'),
    ('S', 'secondary'),
    ('O', 'other')

]

CATEGORY_CHOICES = [
    ('NW', 'New'),
    ('SH', 'Secondhand'),
    ('A', 'Accesories')
]




class Kind(models.Model):
    sign = models.CharField(max_length=50)
    dn = models.IntegerField()


    def get_all_kinds():
        return Kind.objects.all()

    def __str__(self):
        return self.sign

class Grinch(models.Model):
    name = models.CharField(max_length=50)

    def get_all_grinchs():
        return Grinch.objects.all()

    def __str__(self):
        return self.name



class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    discount_price = models.IntegerField(blank=True, null=True)
    kind = models.ForeignKey(Kind, on_delete=models.CASCADE, default=1)
    grinch = models.ForeignKey(Grinch, on_delete=models.CASCADE, default=0)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=2)
    image = models.ImageField(upload_to='images_axuto')
    description = models.TextField(max_length=100)
    add_info = models.TextField(max_length=120)
    slug = models.SlugField()



    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


    @staticmethod
    def get_all_items():
        return Item.objects.all()


    @staticmethod
    def get_all_items_by_kinddn(kind_dn):
        if kind_dn:
            return Item.objects.filter(kind=kind_dn)
        else:
            return Item.get_all_items()

    @staticmethod
    def get_items_by_id(ids):
        return Item.objects.filter(id__in=ids)

    @staticmethod
    def get_all_items():
        return Item.objects.all()

    @staticmethod
    def get_all_items_by_grinchid(grinch_id):
        if grinch_id:
            return Item.objects.filter(grinch=grinch_id)
        else:
            return Item.get_all_items()

class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()




class Order(models.Model):

    user  = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username



def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)

post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
        <a href="https://www.facebook.com/mdbootstrap" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="" target="_blank">
            <i class="fab fa-youtube mr-3"></i>
        </a>

        <a href="" target="_blank">
            <i class="fab fa-google-plus-g mr-3"></i>
        </a>

        <a href="" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
        </a>

        <a href="" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
        </a>

        <a href="" target="_blank">
            <i class="fab fa-github mr-3"></i>
        </a>

        <a href="" target="_blank">
            <i class="fab fa-codepen mr-3"></i>
        </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> aXuto </a>
    </div>
    <!--/.Copyright-->

</footer>

templates/home.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>aXuto.co.ke</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>



  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image:url({% static 'img/C5.jpg ' %}); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Quality Autoparts</strong>
              </h1>

              <p>
                <strong>Get the best deals at axuto</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>.</strong>
              </p>


            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image:url({% static 'img/C9.jpg ' %}); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Quality Original Autoparts</strong>
              </h1>

              <p>
                <strong>Get the best deals at axuto</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>.</strong>
              </p>


            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image:url({% static 'img/C8.jpg ' %}); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Quality Original Autoparts</strong>
              </h1>

              <p>
                <strong>Get the best deals at axuto</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>.</strong>
              </p>


            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">New Parts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Secondhand Parts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Accesories</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                  class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <!--<div class="badge badge-pill {{ item.get_label_display }}-color"></div>-->
                    </a>
                  </strong>
                </h5>
                <a href="" class="grey-text">
                  <div class="badge badge-pill {{ item.get_label_display }}-color"><h5>{{ item.get_category_display }}</h5></div>
                </a>
                

                <h4 class="font-weight-bold blue-text">
                  <strong>ksh
                    {% if item.discount_price %}
                    {{ item.discount_price }}
                    {% else %}
                    {{ item.price }}
                    {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    </div>
    </main>




  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>

</body>
{% endblock content %}

</html>

templates/index.html
{% extends "base2.html" %}

{% block content %}
{% load static %}
{% static "images" as baseUrl %}







	<!-- Banner -->
<body>
	<div class="banner">
		<div class="banner_background" style="background-image:url({% static 'images/czD.jpg' %})"></div>
		<div class="container fill_height">
			<div class="row fill_height">
				<div class="banner_product_image"><img src="{% static '' %}" alt=""></div>
				<div class="col-lg-5 offset-lg-4 fill_height">
					<div class="banner_content">
						<h1 class="banner_text">Free Fitting</h1>
						<div class="banner_price"><span>Deliver Fee</span>Free Delivery</div>
						<div class="banner_product_name">contact us</div>

					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Characteristics -->

	<div class="characteristics">
		<div class="container">
			<div class="row">

				<!-- Char. Item -->
				<div class="col-lg-3 col-md-6 char_col">

					<div class="char_item d-flex flex-row align-items-center justify-content-start">
						<div class="char_icon"><img src="{% static 'images/char_1.png' %}" alt=""></div>
						<div class="char_content">
							<div class="char_title">Free Delivery</div>
							<div class="char_subtitle">from Ksh 5000</div>
						</div>
					</div>
				</div>

				<!-- Char. Item -->
				<div class="col-lg-3 col-md-6 char_col">

					<div class="char_item d-flex flex-row align-items-center justify-content-start">
						<div class="char_icon"><img src="{% static 'images/char_2.png' %}" alt=""></div>
						<div class="char_content">
							<div class="char_title">Free Delivery</div>
							<div class="char_subtitle">from Ksh 5000</div>
						</div>
					</div>
				</div>

				<!-- Char. Item -->
				<div class="col-lg-3 col-md-6 char_col">

					<div class="char_item d-flex flex-row align-items-center justify-content-start">
						<div class="char_icon"><img src="{% static 'images/char_3.png' %}" alt=""></div>
						<div class="char_content">
							<div class="char_title">Free Delivery</div>
							<div class="char_subtitle">from Ksh 5000</div>
						</div>
					</div>
				</div>

				<!-- Char. Item -->
				<div class="col-lg-3 col-md-6 char_col">

					<div class="char_item d-flex flex-row align-items-center justify-content-start">
						<div class="char_icon"><img src="{% static 'images/char_4.png' %}" alt=""></div>
						<div class="char_content">
							<div class="char_title">Free Delivery</div>
							<div class="char_subtitle">from Ksh 5000</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>



									<section class="text-center mb-4">

										<div class="row wow fadeIn">

											{% for item in items %}
											<div class="col-lg-3 col-md-6 mb-4">

												<div class="card">

													<div class="view overlay">
														{% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
															class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
														<a href="{{ item.get_absolute_url }}">
															<div class="mask rgba-white-slight"></div>
														</a>
													</div>

													<div class="card-body text-center">
														<h5>
															<strong>
																<a href="{{ item.get_absolute_url }}" class="deals_item_category">{{ item.title }}
																	<!--<div class="badge badge-pill {{ item.get_label_display }}-color"></div>-->
																</a>
															</strong>
														</h5>
														<a href="" class="grey-text">
															<div class="badge badge-pill {{ item.get_label_display }}-color">
																<h5>{{ item.get_category_display }}</h5>
															</div>
														</a>


														<h4 class="font-weight-bold blue-text">
															<strong>ksh
																{% if item.discount_price %}
																{{ item.discount_price }}
																{% else %}
																{{ item.price }}
																{% endif %}
															</strong>
														</h4>

													</div>

												</div>

											</div>
											{% endfor %}
										</div>

									</section>



									<!--pagination-->




				{% if items.has_other_pages %}
				<nav class="d-flex justify-content-center wow fadeIn">
					<ul class="pagination pg-blue">

						{% if items.has_previous %}
						<li class="page-item">
							<a class="page-link" href="?page={{ items.previous_page_number }}" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
								<span class="sr-only">Previous</span>
							</a>
						</li>
						{% endif %}

						{% for i in items.paginator.page_range %}
						{% if items.number == i %}
						<li class="page-item active">
							<a class="page-link" href="?page={{ i }}">{{ i }}
								<span class="sr-only">(current)</span>
							</a>
						</li>
						{% endif %}
						{% endfor %}
						{% if items.has_next %}
						<li class="page-item">
							<a class="page-link" href="?page={{ items.next_page_number }}" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
								<span class="sr-only">Next</span>
							</a>
						</li>
						{% endif %}
					</ul>
				</nav>
				{% endif %}
				</div>


</body>
{% endblock content %}
</html>

templates/navbar1.html
{% load cart_template_tags %}
{% load static %}

<!-- Top Bar -->

<div class="top_bar">
	<div class="container">
		<div class="row">
			<div class="top_bar_contact_item"><div class="top_bar_icon"><img src="images/phone.png" alt=""></div>LOGO</div>
			<div class="top_bar_content ml-auto">
				<div class="top_bar_menu">
					<ul class="standard_dropdown top_bar_dropdown">

					</ul>
				</div>
				<div class="top_bar_user">
					<div class="user_icon"><img src="{% static 'images/user.svg' %}" alt=""></div>
					{% if request.user.is_authenticated %}
					<div><a href="{% url 'account_logout' %}">logout</a></div>
					{% else %}
					<div><a href="{% url 'account_login' %}">login</a></div>
					<div><a href="{% url 'account_signup' %}">signup</a></div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
</div>

<!-- Header Main -->

<div class="header_main">
	<div class="container">
		<div class="row">

			<!-- Logo -->
			<div class="col-lg-2 col-sm-3 col-3 order-1">
				<div class="logo_container">
					<div class="logo"><a href="/">partsafi</a></div>
				</div>
			</div>

			<!-- Search -->
			<div class="col-lg-6 col-12 order-lg-2 order-3 text-lg-left text-right">
				<div class="header_search">
					<div class="header_search_content">
						<div class="header_search_form_container">
							<form action="/search/" method="post" class="header_search_form clearfix">
							{% csrf_token %}
								<input type="text" id="query" required="required" class="header_search_input"
									placeholder="search">
									<select name="catid">
								<div class="custom_dropdown">
									<div class="custom_dropdown_list">
										<span class="custom_dropdown_placeholder clc">All Categories</span>
										<i class="fas fa-chevron-down"></i>
										<ul class="custom_list clc">
											{% for grinch in grinchs %}
											<li><a class="clc" href="/?grinch={{grinch.id}}">{{ grinch.name }}</a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
								<button type="submit" class="header_search_button trans_300" value="Submit"><img
										src="{% static 'images/search.png' %}" alt=""></button>
							</form>
						</div>
					</div>
				</div>
			</div>


			<!-- Wishlist -->
			{% if request.user.is_authenticated %}
			<div class="col-lg-4 col-9 order-lg-3 order-2 text-lg-left text-right">
				<div class="wishlist_cart d-flex flex-row align-items-center justify-content-end">
					<div class="wishlist d-flex flex-row align-items-center justify-content-end">
						<div class="wishlist_icon"><img src="{% static 'images/checkout.png' %}" alt=""></div>
						<div class="wishlist_content">
							<div class="wishlist_text"><a href="/checkout">Checkout</a></div>
						</div>
					</div>

					<!-- Cart -->

					<div class="cart">
						<div class="cart_container d-flex flex-row align-items-center justify-content-end">
							<div class="cart_icon">
								<img src="{% static 'images/cart1.png' %}" alt="">
								<div class="cart_count"><span>{{ request.user|cart_item_count }}</span></div>
							</div>
							<div class="cart_content">
								<div class="cart_text"><a href="{% url 'core:order-summary' %}">Cart</a></div>

							</div>
						</div>
					</div>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>

<nav class="main_nav">
	<div class="container">
		<div class="row">
			<div class="col">

				<div class="main_nav_content d-flex flex-row">

					<!-- Categories Menu -->

					<div class="cat_menu_container">
						<div class="cat_menu_title d-flex flex-row align-items-center justify-content-start">
							<div class="cat_burger"><span></span><span></span><span></span></div>
							<div class="cat_menu_text" href="">categories</div>
						</div>

						<ul class="cat_menu">

						</ul>
					</div>

					<!-- Main Nav Menu -->

					<div class="main_nav_menu ml-auto">
						<ul class="standard_dropdown main_nav_dropdown">
							{% for kind in kinds %}
							<li><a href="/?kind={{kind.dn}}">{{ kind.sign}}<i class="fas fa-chevron-down"></i></a></li>
							{% endfor %}

						</ul>
					</div>

					<!-- Menu Trigger -->

					<div class="menu_trigger_container ml-auto">
						<div class="menu_trigger d-flex flex-row align-items-center justify-content-end">
							<div class="menu_burger">
								<div class="menu_trigger_text">menu</div>
								<div class="cat_burger menu_burger_inner"><span></span><span></span><span></span></div>
							</div>
						</div>
					</div>
b
				</div>
			</div>
		</div>
	</div>
</nav>


!-- Menu Trigger -->

                    <div class="menu_trigger_container ml-auto">
                        <div class="menu_trigger d-flex flex-row align-items-center justify-content-end">
                            <div class="menu_burger">
                                <div class="menu_trigger_text"></div>
                                <div class="cat_burger menu_burger_inner"><span></span><span></span><span></span></div>
                            </div>
                        </div>



</nav>
<!-- Menu -->

    <div class="page_menu">
        <div class="container">
            <div class="row">
                <div class="col">

                    <div class="page_menu_content">

                        <div class="page_menu_search">
                            <form action="#">
                                <input type="search" required="required" class="page_menu_search_input"
                                    placeholder="Search for products...">
                            </form>
                        </div>
                        <ul class="page_menu_nav">
                            <li class="page_menu_item has-children">
                                <a href="#"><i ></i></a>
                                <ul class="page_menu_selection">
                                    <li><a href="#"><i class="fa fa-angle-down"></i></a></li>

                                </ul>
                            </li>
                            <li class="page_menu_item has-children">
                                <a href="#"><i ></i></a>
                                <ul class="page_menu_selection">
                                    <li><a href="#"><i class="fa fa-angle-down"></i></a></li>

                                </ul>
                            </li>
                            <li class="page_menu_item">
                                <a href="#"><i ></i></a>
                            </li>
                            <li class="page_menu_item has-children">
                                <a href="#"><i ></i></a>
                                <ul class="page_menu_selection">
                                    <li><a href="#"><i ></i></a></li>
                                    <li class="page_menu_item has-children">
                                        <a href="#"><i ></i></a>
                                        <ul class="page_menu_selection">
                                            <li><a href="#"><i ></i></a></li>

                                        </ul>
                                    </li>

                                </ul>
                            </li>
                            <li class="page_menu_item has-children">
                                <a href="#"><i ></i></a>
                                <ul class="page_menu_selection">
                                    <li><a href="#"><i ></i></a></li>

                                </ul>
                            </li>
                            <li class="page_menu_item has-children">
                                <a href="#"><i ></i></a>
                                <ul class="page_menu_selection">
                                    <li><a href="#"><i ></i></a></li>

                                </ul>
                            </li>
                            <li class="page_menu_item"><a href="blog.html"><i ></i></a>
                            </li>
                            <li class="page_menu_item"><a href="contact.html"><i
                                        ></i></a></li>
                        </ul>


                </div>
            </div>
        </div>
    </div>

	</header>